### PR TITLE
Raise Exception when default cloud storage pipeline is not set

### LINKED ISSUE #43: _write_json_blob can fail when default cloud storage bucket is not set
There is a bug in `_write_json_blob` when `app_identity.get_default_gcs_bucket_name()` returns `None`.

This only affects pipelines that need to store large data when yielding children.
This was probably introduced with #18 when removing the Files API.

## Traceback
```python
Bad child arguments. AttributeError: 'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/base/data/home/apps/s~xx/back:29.385854452397669105/lib/pipeline/pipeline.py", line 2283, in evaluate
    _generate_args(sub_stage, future, self.queue_name, self.base_path)
  File "/base/data/home/apps/s~xx/back:29.385854452397669105/lib/pipeline/pipeline.py", line 1403, in _generate_args
    params_blob = _write_json_blob(params_encoded, pipeline.pipeline_id)
  File "/base/data/home/apps/s~xx/back:29.385854452397669105/lib/pipeline/pipeline.py", line 1256, in _write_json_blob
    file_name = posixpath.join(*path_components)
  File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/posixpath.py", line 75, in join
    if b.startswith('/'):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

### PR DESCRIPTION
**Pull request by soundofjw**
Fixes #43 [`_write_json_blob`] by supplying a default bucket name when `app_identity.get_default_gcs_bucket_name()` returns `None`.

Related to changes introduced by #37.

### CODE REVIEW

**Comment by someone1** [comment]
I don't think that is the right approach? Every new project (From my understanding) should come with a default bucket enabled by default. If your project doesn't have one, you can follow the directions here to activate it: https://cloud.google.com/appengine/docs/java/googlecloudstorageclient/activate

assuming `'default'` as the default name is wrong unless this is a reserved keyword to point towards something else?

**Comment by tkaitchuck** [comment]
AIRK: 'default' is keyword used to indicate that it should call that same API to get the default bucket. If it is returning null, because there is no default bucket, this change is not going to help.

**Comment by soundofjw** [comment]
Thanks for the feedback.
On my side, this did fix the change, and I do not have a bucket called 'default'.

That said I'm not sure of how to activate a default bucket on the new console, and the old console, while it has the section mentioned by @someone1, it lacks any way to make the change.

**For this PR:**
Would it be appropriate to simply catch the `None` response and raise an Exception that indicates the situation?

Cheers !

**Comment by soundofjw** [comment]
Updated PR + name. :+1:
