### ISSUE TITLE
_write_json_blob can fail when default cloud storage bucket is not set

### ISSUE THREAD

**Issue by soundofjw** [GoogleCloudPlatform/appengine-pipelines#43]
There is a bug in `_write_json_blob` when `app_identity.get_default_gcs_bucket_name()` returns `None`.

This only affects pipelines that need to store large data when yielding children.
This was probably introduced with #18 when removing the Files API.

## Traceback
```python
Bad child arguments. AttributeError: 'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/base/data/home/apps/s~xx/back:29.385854452397669105/lib/pipeline/pipeline.py", line 2283, in evaluate
    _generate_args(sub_stage, future, self.queue_name, self.base_path)
  File "/base/data/home/apps/s~xx/back:29.385854452397669105/lib/pipeline/pipeline.py", line 1403, in _generate_args
    params_blob = _write_json_blob(params_encoded, pipeline.pipeline_id)
  File "/base/data/home/apps/s~xx/back:29.385854452397669105/lib/pipeline/pipeline.py", line 1256, in _write_json_blob
    file_name = posixpath.join(*path_components)
  File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/posixpath.py", line 75, in join
    if b.startswith('/'):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by soundofjw** [comment]
It seems like `pipeline.py:1250` could be changed to:
```python
default_bucket = app_identity.get_default_gcs_bucket_name() or "default"
```

but I'm not sure how we feel about assuming the default bucket name.
